# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35ce8dd219110e5d993de49878eadc5a3fe67866fc99b9967900429eee0367c739e8610803f648d30852974cbdc19c28a075b1f9316211dadbf6cf27181bd44a

test:
  secret_key_base: 8ec14213d21d0fc0e3a15dcfb9aceb1c4315a14b5fb2b485c2c86b8e569d7da93eb9e16ee73ec1410f6f2e00ea3b43a7f7161a55c11e4d4ba8a1bf7fafeeda65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
